### ISSUE TITLE
Determine how many granules exist over this time and area of interest

### ISSUE THREAD

**Issue by Fumeng-zh** [nsidc/NSIDC-Data-Access-Notebook#10] opened 2023-06-28 13:22 UTC
I run the Customize and Access NSIDC Data to download the data, but an error occured in the part of Determine how many granules exist over this time and area of interest.
![微信图片_20230628152039](https://github.com/nsidc/NSIDC-Data-Access-Notebook/assets/134322614/2c8e2c67-bf7a-4652-90c8-110e75fc566f)
![微信图片_20230628152118](https://github.com/nsidc/NSIDC-Data-Access-Notebook/assets/134322614/baa8aec0-a9a5-4af7-b0eb-79fcb8615a25)
Is there something wrong? all the parameters are default.

**Comment by Fumeng-zh** [comment] 2023-06-29 09:32
The results is empty, is there somthing wrong with the granule_search_url = 'https://cmr.earthdata.nasa.gov/search/granules', because this link returns an error.

**Comment by MattF-NSIDC** [comment] 2023-06-29 16:50
That value for `granule_search_url` looks right. When you click that link, you're getting an error because you haven't passed any search parameters. The code above is doing some extra work to pass those parameters to the server with `requests.get(..., params=search_params, ...)` and that is causing the request URL to be modified to add the key-value pairs in `search_params` as URL query parameters. Example:

```
>>> response = requests.get('https://example.com', params={'foo': 'bar'})
>>> response.request.url
'https://example.com/?foo=bar'
>>> response.ok
True
>>> response.status_code
200
>>> response.content
b'<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset="utf-8" />\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <style type="text/css">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.</p>\n    <p><a href="https://www.iana.org/domains/example">More information...</a></p>\n</div>\n</body>\n</html>\n'
```

Can you please provide:

* `response.request.url`: The actual URL the code is querying
* `response.ok`: Whether the query was successful
* `response.content`: The raw content received from the server. If the content is not JSON (as in the example above), the `json.loads` step would fail.

I think the issue may be with the data you entered; I was able to reproduce this issue by specifying an invalid bounding box.

@asteiker I think we need a validity check before trying to access  `results['feed']`:

```python
    if 'feed' not in results:
        # An error occurred, handle!
        # should we check before json.loads() and print `response.content` instead of `results`?
        # That way if we receive invalid JSON, we can see what the response looks like instead
        # of failing with:
        #     json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
        print(f'An error occurred: {results["errors"]}')
        break # or raise? ¯\_(ツ)_/¯
```

**Comment by Fumeng-zh** [comment] 2023-06-29 18:45
Thanks for your answer, it can work now!

Matt Fisher ***@***.***> 于2023年6月29日周四 18:50写道：

**Comment by MattF-NSIDC** [comment] 2023-06-29 21:22
Great! Thanks for surfacing this issue :) I'm going to close this issue and open a new one for the error handling.

**Closed by MattF-NSIDC** 2023-06-29 21:22 UTC

**Comment by andypbarrett** [comment] 2024-02-05 18:41
This search should be replaced with `earthaccess`.  I have a candidate workflow [here](https://github.com/nsidc/NSIDC-Data-Access-Notebook/blob/update-notebook-with-earthaccess/notebooks/test_smap_request.ipynb)

I've added a class to handle Service capabilities as well.  Maybe a plugin?
